name: Label Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  pull-requests: write

jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - name: Remove semver labels from Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        uses: actions/github-script@v7
        with:
          script: |
            const semverLabels = ['major', 'minor', 'patch'];
            const prNumber = context.payload.pull_request.number;

            for (const label of semverLabels) {
              try {
                await github.rest.issues.removeLabel({
                  ...context.repo,
                  issue_number: prNumber,
                  name: label
                });
              } catch (_) {}
            }

      - name: Check for exactly one version label
        uses: actions/github-script@v7
        with:
          script: |
            const validLabels = ['major', 'minor', 'patch', 'dependencies', 'skip-changelog'];
            const prLabels = context.payload.pull_request.labels;

            const matchingLabels = prLabels.filter(label => validLabels.has(label.name));

            if (matchingLabels.length !== 1) {
              core.setFailed(`One of the following labels is required: ${[...validLabels].join(', ')}. Found ${matchingLabels.length} matching labels.`);
            } else {
              console.log(`Success: Found exactly one valid label: "${matchingLabels[0].name}".`);
            }
